# Generated by Django 4.0.2 on 2022-02-18 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_price', models.IntegerField(default=0)),
                ('batting_style', models.CharField(choices=[('Right Handed Batsman', 'Right Handed Batsman'), ('Left Handed Batsman', 'Left Handed Batsman')], default='', max_length=100)),
                ('country', models.CharField(default='India', max_length=20)),
                ('current_price', models.IntegerField(default=0)),
                ('debut_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=user_info.models.current_year)),
                ('profile', models.TextField(null=True)),
                ('name', models.CharField(default=None, max_length=50)),
                ('player_img', models.TextField(null=True)),
                ('type', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('Wicket Keeper', 'Wicket Keeper'), ('All Rounder', 'All Rounder')], default='', max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Start_Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('money', models.IntegerField(default=1000000000)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('player_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_info.player')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
