# Generated by Django 4.0.1 on 2022-02-03 05:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='user_acc',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
            preserve_default=False,
        ),
    ]
