# Generated by Django 4.0.2 on 2022-02-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_alter_player_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_owner',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
