# Generated by Django 4.0.2 on 2022-02-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_loggedinuser_delete_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_stat',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_info.player'),
        ),
    ]
