# Generated by Django 4.0.2 on 2022-02-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_alter_player_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='odi_ranking',
        ),
        migrations.RemoveField(
            model_name='player',
            name='t20_ranking',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_ranking',
        ),
        migrations.DeleteModel(
            name='Ipl_stat',
        ),
    ]
