# Generated by Django 4.0.2 on 2022-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_remove_player_odi_ranking_remove_player_t20_ranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_owner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
