# Generated by Django 4.0.2 on 2022-02-06 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_info', '0004_alter_test_stat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_owner',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_info.user_data'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
