# Generated by Django 4.0.2 on 2022-02-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_alter_player_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_owner',
            name='player_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_info.player'),
        ),
        migrations.AlterField(
            model_name='player_owner',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.user_data'),
        ),
    ]
