# Generated by Django 4.0.2 on 2022-02-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_alter_player_owner_user_id_alter_user_data_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t20_stat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='test_stat',
            name='id',
        ),
        migrations.DeleteModel(
            name='Odi_stat',
        ),
        migrations.DeleteModel(
            name='T20_stat',
        ),
        migrations.DeleteModel(
            name='Test_stat',
        ),
    ]
