# Generated by Django 4.0.2 on 2022-02-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_remove_t20_stat_id_remove_test_stat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='odi_ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='t20_ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='test_ranking',
            field=models.IntegerField(default=0),
        ),
    ]
