# Generated by Django 4.0.2 on 2022-02-17 19:44

from django.db import migrations, models
import user_info.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_alter_user_data_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='base_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='debut_year',
            field=models.BigIntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=user_info.models.current_year),
        ),
        migrations.AlterField(
            model_name='player_owner',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='money',
            field=models.BigIntegerField(default=2500000000),
        ),
    ]
