version: '3'
services:
    django:
      container_name: django_server
      build: 
        context: esummit22
      environment:
        - DJANGO_SETTINGS_MODULE=ipl_auction.settings
      expose:
        - "8000"
      volumes:
        - static_volume:/app/staticfiles/
        - ./esummit22:/app

      command: bash -c "cd /app && python manage.py makemigrations && python manage.py migrate && daphne ipl_auction.asgi:application --bind=0.0.0.0"
      depends_on:
        - db
    db:
      image: postgres:alpine
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=ipl_auction
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=nilesh  
    nginx:
      image: nginx:latest
      container_name: ng
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - ./nginx/config/:/etc/nginx/conf.d
        - static_volume:/app/staticfiles/
      depends_on:
        - django
        - db
volumes:
  static_volume:
