version: '3'
services:
    django:
      container_name: django_server
      build: 
        context: esummit22
      environment:
        - DJANGO_SETTINGS_MODULE=ipl_auction.settings
      ports:
        - "80:8000"
      command: bash -c "cd /app && python manage.py makemigrations && python manage.py migrate && daphne ipl_auction.asgi:application --bind=0.0.0.0:8000"
      depends_on:
        - db
    db:
      image: postgres:alpine
      environment:
        - POSTGRES_DB=ipl_auction
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=nilesh
    # nginx:
    #   image: nginx:latest
    #   container_name: ng
    #   ports:
    #     - "443:443"
    #     - "80:80"
    #   volumes:
    #     - ./config/nginx/:/etc/nginx/conf.d
    #   depends_on:
    #     - django
    #     - db 
    #     - redis

