# Generated by Django 4.0.1 on 2022-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile',
            field=models.TextField(null=True),
        ),
    ]
