# Generated by Django 4.0.1 on 2022-02-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='money',
            field=models.IntegerField(default=5000000),
        ),
    ]
