# Generated by Django 4.0.1 on 2022-02-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_alter_player_active_alter_user_data_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start_Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.BooleanField(default=False)),
            ],
        ),
    ]
